/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_asus_pc_javacallc_JNI */

#ifndef _Included_com_example_asus_pc_javacallc_JNI
#define _Included_com_example_asus_pc_javacallc_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_asus_pc_javacallc_JNI
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_asus_1pc_javacallc_JNI_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_asus_pc_javacallc_JNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_asus_1pc_javacallc_JNI_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_asus_pc_javacallc_JNI
 * Method:    increseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_asus_1pc_javacallc_JNI_increseArrayEles
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
