/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_asus_pc_jnitest_JNIS */

#ifndef _Included_com_example_asus_pc_jnitest_JNIS
#define _Included_com_example_asus_pc_jnitest_JNIS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_asus_pc_jnitest_JNIS
 * Method:    helloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_asus_1pc_jnitest_JNIS_helloJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
